jobs:
  - name: mohit-1
    type: manifest
    on_success:
      - script: echo 'this is a success!!!'
      #- NOTIFY: myEmail
      #- NOTIFY: hipchat
      #- NOTIFY: irc
      #- NOTIFY: slackNotification
  #  on_start:
      #- NOTIFY: myEmail
      #- NOTIFY: hipchat
      #- NOTIFY: irc
      #- NOTIFY: slackNotification
  #  on_failure:
      #- NOTIFY: myEmail
      #- NOTIFY: hipchat
      #- NOTIFY: irc
      #- NOTIFY: slackNotification
    #always:
    #  - NOTIFY: hipchat
    #  - NOTIFY: irc
    steps:
      - IN: box-nginx
      - IN: dv-params
  #    - IN: trigger-dv-man

  - name: mohit-2
    type: manifest
    steps:
      - IN: box-sn
      - IN: mohit-1
      - IN: dv-params

    #on_start:
    #  - NOTIFY: myEmail
    #on_success:
    #  - NOTIFY: irc
    flags:
      - manifestFlag
      - deployFlag
  
  # - name: ecs-deploy-mohit
  #   type: deploy
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_success:
  #     - NOTIFY: slackNotification
  #     - SCRIPT: echo "this is a success"
  #   on_failure:
  #     - NOTIFY: myEmail
  #     - script: echo "hello there"
  #   steps:
  #     - IN: mohit-2
  #     - IN: ecs-cluster
  #     - TASK: managed
        # deployMethod: upgrade

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  #- name: aws-deploy-1
  #  type: deploy
  #  on_start:
  #    - NOTIFY: slackNotification
  #  on_success:
  #    - NOTIFY: slackNotification
  #  steps:
  #    - IN: mohit-2
  #    - IN: tri-aws
  #    - IN: scale
      #- IN: box-opts
  #    - TASK: managed
  #      deployMethod: blueGreen

  #- name: tri-deploy-1
  #  type: deploy
  #  on_success:
  #    - NOTIFY: slackNotification
  #  steps:
  #    - IN: mohit-2
     #- IN: mohit-1
  #    - IN: tri-cluster
      #- IN: box-opts
  #    - TASK: managed
  #      deployMethod: upgrade

  # - name: tri-deploy-2
  #   type: tripubDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: gkeDeploy-mohit
  #   type: deploy
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_success:
  #     - NOTIFY: slackNotification
  #   on_failure:
  #     - NOTIFY: myEmail
  #   steps:
  #     - IN: mohit-1
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  #- name: ddc-deploy-nginx
  #  type: deploy
  #  on_success:
  #    - script: echo 'this is a success'
  #    - NOTIFY: myEmail
  #    - NOTIFY: hipchat
  #    - NOTIFY: irc
  #    - NOTIFY: slackNotification
  #  on_start:
  #    - NOTIFY: myEmail
  #    - NOTIFY: hipchat
  #    - NOTIFY: irc
  #    - NOTIFY: slackNotification
  #  on_failure:
  #    - NOTIFY: myEmail
  #    - NOTIFY: hipchat
  #    - NOTIFY: irc
  #    - NOTIFY: slackNotification
  #  steps:
  #   - IN: ddc-cluster
  #    - IN: mohit-2
       #- IN: mohit-2
       #- IN: scale
  #  flags:
  #    - deployFlag
      


  #- name: ddc-deploy-boxsn
  #  type: deploy
  #  on_start:
  #    - NOTIFY: slackNotification
  #  on_success:
      #- NOTIFY: myEmail
  #  on_failure:
  #    - NOTIFY: slackNotification
  #  steps:
  #    - IN: ddc-cluster
      #- IN: mohit-1
  #    - IN: mohit-2
      #- IN: scale

  # - name: dcl-deploy
  #   type: deploy
  #   on_success:
  #     - NOTIFY: slackNotification
  #     - NOTIFY: myEmail
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_failure:
  #     - NOTIFY: myEmail
  #     - NOTIFY: slackNotification
  #   steps:
  #     - IN: mohit-1
  #     - IN: dcl-cluster
  #     - TASK: managed
